theme: jekyll-theme-minimal
title: Hydro Pi-nics Sensor Data
description: A GitHub repository for the Champlain College ITS Capstone by Miranda Pagarelski. Original project created by Connor Merchant and Sam Johnson.
